channels:
  - conda-forge
  - giuliorossetti
  - defaults
dependencies:
  - python=3.8
  - netcdf4=1.5
  - scipy=1.8
  - matplotlib=3.5
  - networkx=2.7
  - joblib=1.1
  - cartopy=0.18
  - numpy=1.20
  - cdlib=0.2.6
  - wurlitzer=3.0  # For infomap in cdlib
  - pip:
    - infomap~=2.2
